# Generated by Django 5.2.10 on 2026-07-30 19:19

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0019_blogpage_body_render_cache_key_and_more"),
        ("wagtailcore", "0094_alter_page_locale"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogAuthor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ghost_id",
                    models.CharField(blank=True, max_length=64, null=True, unique=True),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("bio", models.TextField(blank=True)),
                ("website", models.URLField(blank=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="BlogTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ghost_id",
                    models.CharField(blank=True, max_length=64, null=True, unique=True),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ContentPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "ghost_id",
                    models.CharField(blank=True, max_length=64, null=True, unique=True),
                ),
                ("ghost_uuid", models.UUIDField(blank=True, null=True, unique=True)),
                ("ghost_created_at", models.DateTimeField(blank=True, null=True)),
                ("ghost_updated_at", models.DateTimeField(blank=True, null=True)),
                ("ghost_published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [
                            ("markdown", 0),
                            ("paragraph", 1),
                            ("heading", 2),
                            ("image", 5),
                            ("code", 8),
                            ("raw_html", 9),
                            ("quote", 7),
                            ("glossary", 17),
                            ("takeaway", 21),
                            ("applet_embed", 28),
                        ],
                        blank=True,
                        block_lookup={
                            0: ("wagtailmarkdown.blocks.MarkdownBlock", (), {}),
                            1: ("wagtail.blocks.RichTextBlock", (), {}),
                            2: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"form_classname": "title"},
                            ),
                            3: (
                                "wagtail.images.blocks.ImageChooserBlock",
                                (),
                                {"required": True},
                            ),
                            4: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Optional caption shown under the image.",
                                    "required": False,
                                },
                            ),
                            5: (
                                "wagtail.blocks.StructBlock",
                                [[("image", 3), ("caption", 4)]],
                                {},
                            ),
                            6: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": (
                                        "Language hint for syntax highlighting (e.g. python, js)."
                                    ),
                                    "required": False,
                                },
                            ),
                            7: ("wagtail.blocks.TextBlock", (), {}),
                            8: (
                                "wagtail.blocks.StructBlock",
                                [[("language", 6), ("code", 7)]],
                                {},
                            ),
                            9: ("wagtail.blocks.RawHTMLBlock", (), {}),
                            10: ("wagtail.blocks.CharBlock", (), {"required": True}),
                            11: ("wagtail.blocks.TextBlock", (), {"required": True}),
                            12: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Optional aliases (comma-separated).",
                                    "required": False,
                                },
                            ),
                            13: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("term", 10),
                                        ("definition", 11),
                                        ("aliases", 12),
                                    ]
                                ],
                                {},
                            ),
                            14: (
                                "wagtail.blocks.ListBlock",
                                (13,),
                                {"help_text": "Glossary terms for this post."},
                            ),
                            15: (
                                "wagtail.blocks.BooleanBlock",
                                (),
                                {
                                    "default": False,
                                    "help_text": "Auto-link matching terms in the post body.",
                                    "required": False,
                                },
                            ),
                            16: (
                                "wagtail.blocks.BooleanBlock",
                                (),
                                {
                                    "default": False,
                                    "help_text": "Show a glossary list at this position.",
                                    "required": False,
                                },
                            ),
                            17: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("terms", 14),
                                        ("auto_link", 15),
                                        ("show_list", 16),
                                    ]
                                ],
                                {},
                            ),
                            18: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Optional label (e.g. Key takeaway).",
                                    "required": False,
                                },
                            ),
                            19: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("blue", "Blue"),
                                        ("purple", "Purple"),
                                        ("pink", "Pink"),
                                        ("gold", "Gold"),
                                    ],
                                    "help_text": "Accent color for the callout.",
                                    "required": False,
                                },
                            ),
                            20: (
                                "wagtailmarkdown.blocks.MarkdownBlock",
                                (),
                                {"required": True},
                            ),
                            21: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("title", 18),
                                        ("color", 19),
                                        ("body", 20),
                                    ]
                                ],
                                {},
                            ),
                            22: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Accessible title for the iframe content.",
                                    "required": True,
                                },
                            ),
                            23: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": (
                                        "Path to an applet under /static/applets/ "
                                        "(for example /static/applets/loser-winner.html)."
                                    ),
                                    "required": True,
                                },
                            ),
                            24: (
                                "wagtail.blocks.BooleanBlock",
                                (),
                                {
                                    "default": True,
                                    "help_text": (
                                        "Lazy-load the iframe (recommended). "
                                        "Disable only when immediate load is required."
                                    ),
                                    "required": False,
                                },
                            ),
                            25: (
                                "wagtail.blocks.BooleanBlock",
                                (),
                                {
                                    "default": False,
                                    "help_text": (
                                        "Ignore max height and auto-resize iframe "
                                        "to full applet content height."
                                    ),
                                    "required": False,
                                },
                            ),
                            26: (
                                "wagtail.blocks.IntegerBlock",
                                (),
                                {
                                    "help_text": (
                                        "Optional maximum iframe height (px). "
                                        "If applet content exceeds this, it scrolls "
                                        "inside the frame."
                                    ),
                                    "min_value": 120,
                                    "required": False,
                                },
                            ),
                            27: (
                                "wagtail.blocks.TextBlock",
                                (),
                                {
                                    "help_text": (
                                        "Optional inline style overrides for the iframe "
                                        "element (CSS declarations)."
                                    ),
                                    "required": False,
                                },
                            ),
                            28: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("title", 22),
                                        ("src", 23),
                                        ("lazy_load", 24),
                                        ("use_full_height", 25),
                                        ("max_height", 26),
                                        ("style_overrides", 27),
                                    ]
                                ],
                                {},
                            ),
                        },
                    ),
                ),
            ],
            options={
                "verbose_name": "Content Page",
            },
            bases=("wagtailcore.page", models.Model),
        ),
        migrations.AddField(
            model_name="blogindexpage",
            name="default_author_name",
            field=models.CharField(
                blank=True,
                help_text=("Default author name for site metadata and unattributed posts."),
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="blogpage",
            name="ghost_created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="blogpage",
            name="ghost_id",
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="blogpage",
            name="ghost_published_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="blogpage",
            name="ghost_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="blogpage",
            name="ghost_uuid",
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="blogpage",
            name="authors",
            field=modelcluster.fields.ParentalManyToManyField(
                blank=True,
                related_name="blog_pages",
                to="blog.blogauthor",
            ),
        ),
        migrations.AddField(
            model_name="blogpage",
            name="is_featured",
            field=models.BooleanField(
                default=False,
                help_text="Feature this post in editorial selections.",
            ),
        ),
        migrations.AddField(
            model_name="blogpage",
            name="tags",
            field=modelcluster.fields.ParentalManyToManyField(
                blank=True,
                related_name="blog_pages",
                to="blog.blogtag",
            ),
        ),
        migrations.CreateModel(
            name="GhostImageImport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ghost_path", models.CharField(max_length=1024, unique=True)),
                ("source_sha256", models.CharField(max_length=64)),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "ordering": ["ghost_path"],
            },
        ),
    ]
