# Generated by Django 5.2.10 on 2026-07-31 03:17

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_blogauthor_blogtag_contentpage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(help_text='Stable public URL segment used under /series/.', max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('ongoing', 'Ongoing'), ('complete', 'Complete')], default='ongoing', max_length=16)),
                ('next_up', models.CharField(blank=True, help_text='Optional public note about the next unpublished part.', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Blog series',
                'verbose_name_plural': 'Blog series',
                'ordering': ['title', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='BlogSeriesMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('is_primary', models.BooleanField(default=False, help_text='Use this series for the post band and in-series navigation.')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series_memberships', to='blog.blogpage')),
                ('series', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='blog.blogseries')),
            ],
            options={
                'ordering': ['sort_order', 'pk'],
                'constraints': [models.UniqueConstraint(fields=('series', 'page'), name='blog_unique_series_page'), models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('page',), name='blog_one_primary_series_per_page')],
            },
        ),
    ]
