# Generated by Django 5.2.10 on 2026-07-30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0021_blogseries_blogseriesmembership"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="WagtailImageImport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_namespace", models.CharField(max_length=128)),
                ("source_image_id", models.PositiveBigIntegerField()),
                ("source_sha256", models.CharField(max_length=64)),
                ("stored_sha256", models.CharField(max_length=64)),
                ("imported_at", models.DateTimeField(auto_now=True)),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "ordering": ["source_namespace", "source_image_id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("source_namespace", "source_image_id"),
                        name="blog_unique_wagtail_image_source",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="WagtailPageImport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_namespace", models.CharField(max_length=128)),
                ("source_page_id", models.PositiveBigIntegerField()),
                ("source_live_sha256", models.CharField(max_length=64)),
                ("source_draft_sha256", models.CharField(blank=True, max_length=64)),
                ("source_first_published_at", models.DateTimeField()),
                ("source_last_published_at", models.DateTimeField()),
                ("target_live_sha256", models.CharField(max_length=64)),
                ("target_draft_sha256", models.CharField(blank=True, max_length=64)),
                ("imported_at", models.DateTimeField(auto_now=True)),
                (
                    "page",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="wagtail_import",
                        to="blog.blogpage",
                    ),
                ),
            ],
            options={
                "ordering": ["source_namespace", "source_page_id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("source_namespace", "source_page_id"),
                        name="blog_unique_wagtail_page_source",
                    ),
                ],
            },
        ),
    ]
