# Generated by Django 5.2.10 on 2026-08-01 02:30

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_wagtail_import_mappings'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogindexpage',
            name='signpost_heading',
            field=models.CharField(blank=True, help_text='Landing headline. Falls back to the site name when blank.', max_length=160),
        ),
        migrations.AddField(
            model_name='blogindexpage',
            name='signpost_intro',
            field=models.TextField(blank=True, help_text='Short landing paragraph. Falls back to the site description when blank.'),
        ),
        migrations.AddField(
            model_name='blogindexpage',
            name='signpost_kicker',
            field=models.CharField(blank=True, help_text="Short mono label above the name (e.g. 'software engineer · ml systems').", max_length=120),
        ),
        migrations.CreateModel(
            name='SignpostLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('label', models.CharField(max_length=120)),
                ('url', models.CharField(help_text='Absolute URL (https://…) or a site-relative path (/about/).', max_length=500)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='signpost_links', to='blog.blogindexpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
