# Generated by Django 5.2.10 on 2026-08-01 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_blogindexpage_signpost_heading_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='force_math',
            field=models.BooleanField(default=False, help_text='Force-load KaTeX math rendering on this post even when no math delimiters are detected in the body. Leave unchecked to rely on automatic detection.', verbose_name='Math blog?'),
        ),
    ]
